// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/consequence_scope"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
)

// ConsequenceScopeDelete is the builder for deleting a Consequence_Scope entity.
type ConsequenceScopeDelete struct {
	config
	hooks    []Hook
	mutation *ConsequenceScopeMutation
}

// Where appends a list predicates to the ConsequenceScopeDelete builder.
func (csd *ConsequenceScopeDelete) Where(ps ...predicate.Consequence_Scope) *ConsequenceScopeDelete {
	csd.mutation.Where(ps...)
	return csd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (csd *ConsequenceScopeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, csd.sqlExec, csd.mutation, csd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (csd *ConsequenceScopeDelete) ExecX(ctx context.Context) int {
	n, err := csd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (csd *ConsequenceScopeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(consequence_scope.Table, sqlgraph.NewFieldSpec(consequence_scope.FieldID, field.TypeUUID))
	if ps := csd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, csd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	csd.mutation.done = true
	return affected, err
}

// ConsequenceScopeDeleteOne is the builder for deleting a single Consequence_Scope entity.
type ConsequenceScopeDeleteOne struct {
	csd *ConsequenceScopeDelete
}

// Where appends a list predicates to the ConsequenceScopeDelete builder.
func (csdo *ConsequenceScopeDeleteOne) Where(ps ...predicate.Consequence_Scope) *ConsequenceScopeDeleteOne {
	csdo.csd.mutation.Where(ps...)
	return csdo
}

// Exec executes the deletion query.
func (csdo *ConsequenceScopeDeleteOne) Exec(ctx context.Context) error {
	n, err := csdo.csd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{consequence_scope.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (csdo *ConsequenceScopeDeleteOne) ExecX(ctx context.Context) {
	if err := csdo.Exec(ctx); err != nil {
		panic(err)
	}
}
