// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/demonstrativeexample"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
)

// DemonstrativeExampleDelete is the builder for deleting a DemonstrativeExample entity.
type DemonstrativeExampleDelete struct {
	config
	hooks    []Hook
	mutation *DemonstrativeExampleMutation
}

// Where appends a list predicates to the DemonstrativeExampleDelete builder.
func (ded *DemonstrativeExampleDelete) Where(ps ...predicate.DemonstrativeExample) *DemonstrativeExampleDelete {
	ded.mutation.Where(ps...)
	return ded
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ded *DemonstrativeExampleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ded.sqlExec, ded.mutation, ded.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ded *DemonstrativeExampleDelete) ExecX(ctx context.Context) int {
	n, err := ded.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ded *DemonstrativeExampleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(demonstrativeexample.Table, sqlgraph.NewFieldSpec(demonstrativeexample.FieldID, field.TypeUUID))
	if ps := ded.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ded.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ded.mutation.done = true
	return affected, err
}

// DemonstrativeExampleDeleteOne is the builder for deleting a single DemonstrativeExample entity.
type DemonstrativeExampleDeleteOne struct {
	ded *DemonstrativeExampleDelete
}

// Where appends a list predicates to the DemonstrativeExampleDelete builder.
func (dedo *DemonstrativeExampleDeleteOne) Where(ps ...predicate.DemonstrativeExample) *DemonstrativeExampleDeleteOne {
	dedo.ded.mutation.Where(ps...)
	return dedo
}

// Exec executes the deletion query.
func (dedo *DemonstrativeExampleDeleteOne) Exec(ctx context.Context) error {
	n, err := dedo.ded.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{demonstrativeexample.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dedo *DemonstrativeExampleDeleteOne) ExecX(ctx context.Context) {
	if err := dedo.Exec(ctx); err != nil {
		panic(err)
	}
}
