// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/potentialmitigation"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
)

// PotentialMitigationDelete is the builder for deleting a PotentialMitigation entity.
type PotentialMitigationDelete struct {
	config
	hooks    []Hook
	mutation *PotentialMitigationMutation
}

// Where appends a list predicates to the PotentialMitigationDelete builder.
func (pmd *PotentialMitigationDelete) Where(ps ...predicate.PotentialMitigation) *PotentialMitigationDelete {
	pmd.mutation.Where(ps...)
	return pmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pmd *PotentialMitigationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pmd.sqlExec, pmd.mutation, pmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pmd *PotentialMitigationDelete) ExecX(ctx context.Context) int {
	n, err := pmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pmd *PotentialMitigationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(potentialmitigation.Table, sqlgraph.NewFieldSpec(potentialmitigation.FieldID, field.TypeUUID))
	if ps := pmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pmd.mutation.done = true
	return affected, err
}

// PotentialMitigationDeleteOne is the builder for deleting a single PotentialMitigation entity.
type PotentialMitigationDeleteOne struct {
	pmd *PotentialMitigationDelete
}

// Where appends a list predicates to the PotentialMitigationDelete builder.
func (pmdo *PotentialMitigationDeleteOne) Where(ps ...predicate.PotentialMitigation) *PotentialMitigationDeleteOne {
	pmdo.pmd.mutation.Where(ps...)
	return pmdo
}

// Exec executes the deletion query.
func (pmdo *PotentialMitigationDeleteOne) Exec(ctx context.Context) error {
	n, err := pmdo.pmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{potentialmitigation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pmdo *PotentialMitigationDeleteOne) ExecX(ctx context.Context) {
	if err := pmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
