// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/cwe"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/potentialmitigation"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
)

// PotentialMitigationQuery is the builder for querying PotentialMitigation entities.
type PotentialMitigationQuery struct {
	config
	ctx          *QueryContext
	order        []potentialmitigation.OrderOption
	inters       []Interceptor
	predicates   []predicate.PotentialMitigation
	withCwe      *CWEQuery
	modifiers    []func(*sql.Selector)
	loadTotal    []func(context.Context, []*PotentialMitigation) error
	withNamedCwe map[string]*CWEQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PotentialMitigationQuery builder.
func (pmq *PotentialMitigationQuery) Where(ps ...predicate.PotentialMitigation) *PotentialMitigationQuery {
	pmq.predicates = append(pmq.predicates, ps...)
	return pmq
}

// Limit the number of records to be returned by this query.
func (pmq *PotentialMitigationQuery) Limit(limit int) *PotentialMitigationQuery {
	pmq.ctx.Limit = &limit
	return pmq
}

// Offset to start from.
func (pmq *PotentialMitigationQuery) Offset(offset int) *PotentialMitigationQuery {
	pmq.ctx.Offset = &offset
	return pmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pmq *PotentialMitigationQuery) Unique(unique bool) *PotentialMitigationQuery {
	pmq.ctx.Unique = &unique
	return pmq
}

// Order specifies how the records should be ordered.
func (pmq *PotentialMitigationQuery) Order(o ...potentialmitigation.OrderOption) *PotentialMitigationQuery {
	pmq.order = append(pmq.order, o...)
	return pmq
}

// QueryCwe chains the current query on the "cwe" edge.
func (pmq *PotentialMitigationQuery) QueryCwe() *CWEQuery {
	query := (&CWEClient{config: pmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(potentialmitigation.Table, potentialmitigation.FieldID, selector),
			sqlgraph.To(cwe.Table, cwe.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, potentialmitigation.CweTable, potentialmitigation.CwePrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(pmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PotentialMitigation entity from the query.
// Returns a *NotFoundError when no PotentialMitigation was found.
func (pmq *PotentialMitigationQuery) First(ctx context.Context) (*PotentialMitigation, error) {
	nodes, err := pmq.Limit(1).All(setContextOp(ctx, pmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{potentialmitigation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pmq *PotentialMitigationQuery) FirstX(ctx context.Context) *PotentialMitigation {
	node, err := pmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PotentialMitigation ID from the query.
// Returns a *NotFoundError when no PotentialMitigation ID was found.
func (pmq *PotentialMitigationQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pmq.Limit(1).IDs(setContextOp(ctx, pmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{potentialmitigation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pmq *PotentialMitigationQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PotentialMitigation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PotentialMitigation entity is found.
// Returns a *NotFoundError when no PotentialMitigation entities are found.
func (pmq *PotentialMitigationQuery) Only(ctx context.Context) (*PotentialMitigation, error) {
	nodes, err := pmq.Limit(2).All(setContextOp(ctx, pmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{potentialmitigation.Label}
	default:
		return nil, &NotSingularError{potentialmitigation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pmq *PotentialMitigationQuery) OnlyX(ctx context.Context) *PotentialMitigation {
	node, err := pmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PotentialMitigation ID in the query.
// Returns a *NotSingularError when more than one PotentialMitigation ID is found.
// Returns a *NotFoundError when no entities are found.
func (pmq *PotentialMitigationQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pmq.Limit(2).IDs(setContextOp(ctx, pmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{potentialmitigation.Label}
	default:
		err = &NotSingularError{potentialmitigation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pmq *PotentialMitigationQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PotentialMitigations.
func (pmq *PotentialMitigationQuery) All(ctx context.Context) ([]*PotentialMitigation, error) {
	ctx = setContextOp(ctx, pmq.ctx, ent.OpQueryAll)
	if err := pmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PotentialMitigation, *PotentialMitigationQuery]()
	return withInterceptors[[]*PotentialMitigation](ctx, pmq, qr, pmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pmq *PotentialMitigationQuery) AllX(ctx context.Context) []*PotentialMitigation {
	nodes, err := pmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PotentialMitigation IDs.
func (pmq *PotentialMitigationQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if pmq.ctx.Unique == nil && pmq.path != nil {
		pmq.Unique(true)
	}
	ctx = setContextOp(ctx, pmq.ctx, ent.OpQueryIDs)
	if err = pmq.Select(potentialmitigation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pmq *PotentialMitigationQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pmq *PotentialMitigationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pmq.ctx, ent.OpQueryCount)
	if err := pmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pmq, querierCount[*PotentialMitigationQuery](), pmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pmq *PotentialMitigationQuery) CountX(ctx context.Context) int {
	count, err := pmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pmq *PotentialMitigationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pmq.ctx, ent.OpQueryExist)
	switch _, err := pmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pmq *PotentialMitigationQuery) ExistX(ctx context.Context) bool {
	exist, err := pmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PotentialMitigationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pmq *PotentialMitigationQuery) Clone() *PotentialMitigationQuery {
	if pmq == nil {
		return nil
	}
	return &PotentialMitigationQuery{
		config:     pmq.config,
		ctx:        pmq.ctx.Clone(),
		order:      append([]potentialmitigation.OrderOption{}, pmq.order...),
		inters:     append([]Interceptor{}, pmq.inters...),
		predicates: append([]predicate.PotentialMitigation{}, pmq.predicates...),
		withCwe:    pmq.withCwe.Clone(),
		// clone intermediate query.
		sql:  pmq.sql.Clone(),
		path: pmq.path,
	}
}

// WithCwe tells the query-builder to eager-load the nodes that are connected to
// the "cwe" edge. The optional arguments are used to configure the query builder of the edge.
func (pmq *PotentialMitigationQuery) WithCwe(opts ...func(*CWEQuery)) *PotentialMitigationQuery {
	query := (&CWEClient{config: pmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pmq.withCwe = query
	return pmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Phase string `json:"phase,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PotentialMitigation.Query().
//		GroupBy(potentialmitigation.FieldPhase).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pmq *PotentialMitigationQuery) GroupBy(field string, fields ...string) *PotentialMitigationGroupBy {
	pmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PotentialMitigationGroupBy{build: pmq}
	grbuild.flds = &pmq.ctx.Fields
	grbuild.label = potentialmitigation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Phase string `json:"phase,omitempty"`
//	}
//
//	client.PotentialMitigation.Query().
//		Select(potentialmitigation.FieldPhase).
//		Scan(ctx, &v)
func (pmq *PotentialMitigationQuery) Select(fields ...string) *PotentialMitigationSelect {
	pmq.ctx.Fields = append(pmq.ctx.Fields, fields...)
	sbuild := &PotentialMitigationSelect{PotentialMitigationQuery: pmq}
	sbuild.label = potentialmitigation.Label
	sbuild.flds, sbuild.scan = &pmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PotentialMitigationSelect configured with the given aggregations.
func (pmq *PotentialMitigationQuery) Aggregate(fns ...AggregateFunc) *PotentialMitigationSelect {
	return pmq.Select().Aggregate(fns...)
}

func (pmq *PotentialMitigationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pmq); err != nil {
				return err
			}
		}
	}
	for _, f := range pmq.ctx.Fields {
		if !potentialmitigation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pmq.path != nil {
		prev, err := pmq.path(ctx)
		if err != nil {
			return err
		}
		pmq.sql = prev
	}
	return nil
}

func (pmq *PotentialMitigationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PotentialMitigation, error) {
	var (
		nodes       = []*PotentialMitigation{}
		_spec       = pmq.querySpec()
		loadedTypes = [1]bool{
			pmq.withCwe != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PotentialMitigation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PotentialMitigation{config: pmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(pmq.modifiers) > 0 {
		_spec.Modifiers = pmq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pmq.withCwe; query != nil {
		if err := pmq.loadCwe(ctx, query, nodes,
			func(n *PotentialMitigation) { n.Edges.Cwe = []*CWE{} },
			func(n *PotentialMitigation, e *CWE) { n.Edges.Cwe = append(n.Edges.Cwe, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range pmq.withNamedCwe {
		if err := pmq.loadCwe(ctx, query, nodes,
			func(n *PotentialMitigation) { n.appendNamedCwe(name) },
			func(n *PotentialMitigation, e *CWE) { n.appendNamedCwe(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range pmq.loadTotal {
		if err := pmq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pmq *PotentialMitigationQuery) loadCwe(ctx context.Context, query *CWEQuery, nodes []*PotentialMitigation, init func(*PotentialMitigation), assign func(*PotentialMitigation, *CWE)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*PotentialMitigation)
	nids := make(map[uuid.UUID]map[*PotentialMitigation]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(potentialmitigation.CweTable)
		s.Join(joinT).On(s.C(cwe.FieldID), joinT.C(potentialmitigation.CwePrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(potentialmitigation.CwePrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(potentialmitigation.CwePrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*PotentialMitigation]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*CWE](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "cwe" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (pmq *PotentialMitigationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pmq.querySpec()
	if len(pmq.modifiers) > 0 {
		_spec.Modifiers = pmq.modifiers
	}
	_spec.Node.Columns = pmq.ctx.Fields
	if len(pmq.ctx.Fields) > 0 {
		_spec.Unique = pmq.ctx.Unique != nil && *pmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pmq.driver, _spec)
}

func (pmq *PotentialMitigationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(potentialmitigation.Table, potentialmitigation.Columns, sqlgraph.NewFieldSpec(potentialmitigation.FieldID, field.TypeUUID))
	_spec.From = pmq.sql
	if unique := pmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pmq.path != nil {
		_spec.Unique = true
	}
	if fields := pmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, potentialmitigation.FieldID)
		for i := range fields {
			if fields[i] != potentialmitigation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pmq *PotentialMitigationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pmq.driver.Dialect())
	t1 := builder.Table(potentialmitigation.Table)
	columns := pmq.ctx.Fields
	if len(columns) == 0 {
		columns = potentialmitigation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pmq.sql != nil {
		selector = pmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pmq.ctx.Unique != nil && *pmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pmq.predicates {
		p(selector)
	}
	for _, p := range pmq.order {
		p(selector)
	}
	if offset := pmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedCwe tells the query-builder to eager-load the nodes that are connected to the "cwe"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (pmq *PotentialMitigationQuery) WithNamedCwe(name string, opts ...func(*CWEQuery)) *PotentialMitigationQuery {
	query := (&CWEClient{config: pmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if pmq.withNamedCwe == nil {
		pmq.withNamedCwe = make(map[string]*CWEQuery)
	}
	pmq.withNamedCwe[name] = query
	return pmq
}

// PotentialMitigationGroupBy is the group-by builder for PotentialMitigation entities.
type PotentialMitigationGroupBy struct {
	selector
	build *PotentialMitigationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pmgb *PotentialMitigationGroupBy) Aggregate(fns ...AggregateFunc) *PotentialMitigationGroupBy {
	pmgb.fns = append(pmgb.fns, fns...)
	return pmgb
}

// Scan applies the selector query and scans the result into the given value.
func (pmgb *PotentialMitigationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pmgb.build.ctx, ent.OpQueryGroupBy)
	if err := pmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PotentialMitigationQuery, *PotentialMitigationGroupBy](ctx, pmgb.build, pmgb, pmgb.build.inters, v)
}

func (pmgb *PotentialMitigationGroupBy) sqlScan(ctx context.Context, root *PotentialMitigationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pmgb.fns))
	for _, fn := range pmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pmgb.flds)+len(pmgb.fns))
		for _, f := range *pmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PotentialMitigationSelect is the builder for selecting fields of PotentialMitigation entities.
type PotentialMitigationSelect struct {
	*PotentialMitigationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pms *PotentialMitigationSelect) Aggregate(fns ...AggregateFunc) *PotentialMitigationSelect {
	pms.fns = append(pms.fns, fns...)
	return pms
}

// Scan applies the selector query and scans the result into the given value.
func (pms *PotentialMitigationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pms.ctx, ent.OpQuerySelect)
	if err := pms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PotentialMitigationQuery, *PotentialMitigationSelect](ctx, pms.PotentialMitigationQuery, pms, pms.inters, v)
}

func (pms *PotentialMitigationSelect) sqlScan(ctx context.Context, root *PotentialMitigationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pms.fns))
	for _, fn := range pms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
