// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/certifyvex"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/reachablecode"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/reachablecodeartifact"
)

// ReachableCodeQuery is the builder for querying ReachableCode entities.
type ReachableCodeQuery struct {
	config
	ctx                            *QueryContext
	order                          []reachablecode.OrderOption
	inters                         []Interceptor
	predicates                     []predicate.ReachableCode
	withCertifyVex                 *CertifyVexQuery
	withReachableCodeArtifact      *ReachableCodeArtifactQuery
	modifiers                      []func(*sql.Selector)
	loadTotal                      []func(context.Context, []*ReachableCode) error
	withNamedCertifyVex            map[string]*CertifyVexQuery
	withNamedReachableCodeArtifact map[string]*ReachableCodeArtifactQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReachableCodeQuery builder.
func (rcq *ReachableCodeQuery) Where(ps ...predicate.ReachableCode) *ReachableCodeQuery {
	rcq.predicates = append(rcq.predicates, ps...)
	return rcq
}

// Limit the number of records to be returned by this query.
func (rcq *ReachableCodeQuery) Limit(limit int) *ReachableCodeQuery {
	rcq.ctx.Limit = &limit
	return rcq
}

// Offset to start from.
func (rcq *ReachableCodeQuery) Offset(offset int) *ReachableCodeQuery {
	rcq.ctx.Offset = &offset
	return rcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rcq *ReachableCodeQuery) Unique(unique bool) *ReachableCodeQuery {
	rcq.ctx.Unique = &unique
	return rcq
}

// Order specifies how the records should be ordered.
func (rcq *ReachableCodeQuery) Order(o ...reachablecode.OrderOption) *ReachableCodeQuery {
	rcq.order = append(rcq.order, o...)
	return rcq
}

// QueryCertifyVex chains the current query on the "certify_vex" edge.
func (rcq *ReachableCodeQuery) QueryCertifyVex() *CertifyVexQuery {
	query := (&CertifyVexClient{config: rcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(reachablecode.Table, reachablecode.FieldID, selector),
			sqlgraph.To(certifyvex.Table, certifyvex.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, reachablecode.CertifyVexTable, reachablecode.CertifyVexPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReachableCodeArtifact chains the current query on the "reachable_code_artifact" edge.
func (rcq *ReachableCodeQuery) QueryReachableCodeArtifact() *ReachableCodeArtifactQuery {
	query := (&ReachableCodeArtifactClient{config: rcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(reachablecode.Table, reachablecode.FieldID, selector),
			sqlgraph.To(reachablecodeartifact.Table, reachablecodeartifact.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, reachablecode.ReachableCodeArtifactTable, reachablecode.ReachableCodeArtifactPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ReachableCode entity from the query.
// Returns a *NotFoundError when no ReachableCode was found.
func (rcq *ReachableCodeQuery) First(ctx context.Context) (*ReachableCode, error) {
	nodes, err := rcq.Limit(1).All(setContextOp(ctx, rcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{reachablecode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rcq *ReachableCodeQuery) FirstX(ctx context.Context) *ReachableCode {
	node, err := rcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReachableCode ID from the query.
// Returns a *NotFoundError when no ReachableCode ID was found.
func (rcq *ReachableCodeQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rcq.Limit(1).IDs(setContextOp(ctx, rcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{reachablecode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rcq *ReachableCodeQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := rcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReachableCode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReachableCode entity is found.
// Returns a *NotFoundError when no ReachableCode entities are found.
func (rcq *ReachableCodeQuery) Only(ctx context.Context) (*ReachableCode, error) {
	nodes, err := rcq.Limit(2).All(setContextOp(ctx, rcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{reachablecode.Label}
	default:
		return nil, &NotSingularError{reachablecode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rcq *ReachableCodeQuery) OnlyX(ctx context.Context) *ReachableCode {
	node, err := rcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReachableCode ID in the query.
// Returns a *NotSingularError when more than one ReachableCode ID is found.
// Returns a *NotFoundError when no entities are found.
func (rcq *ReachableCodeQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rcq.Limit(2).IDs(setContextOp(ctx, rcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{reachablecode.Label}
	default:
		err = &NotSingularError{reachablecode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rcq *ReachableCodeQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := rcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReachableCodes.
func (rcq *ReachableCodeQuery) All(ctx context.Context) ([]*ReachableCode, error) {
	ctx = setContextOp(ctx, rcq.ctx, ent.OpQueryAll)
	if err := rcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReachableCode, *ReachableCodeQuery]()
	return withInterceptors[[]*ReachableCode](ctx, rcq, qr, rcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rcq *ReachableCodeQuery) AllX(ctx context.Context) []*ReachableCode {
	nodes, err := rcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReachableCode IDs.
func (rcq *ReachableCodeQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if rcq.ctx.Unique == nil && rcq.path != nil {
		rcq.Unique(true)
	}
	ctx = setContextOp(ctx, rcq.ctx, ent.OpQueryIDs)
	if err = rcq.Select(reachablecode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rcq *ReachableCodeQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := rcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rcq *ReachableCodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rcq.ctx, ent.OpQueryCount)
	if err := rcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rcq, querierCount[*ReachableCodeQuery](), rcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rcq *ReachableCodeQuery) CountX(ctx context.Context) int {
	count, err := rcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rcq *ReachableCodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rcq.ctx, ent.OpQueryExist)
	switch _, err := rcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rcq *ReachableCodeQuery) ExistX(ctx context.Context) bool {
	exist, err := rcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReachableCodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rcq *ReachableCodeQuery) Clone() *ReachableCodeQuery {
	if rcq == nil {
		return nil
	}
	return &ReachableCodeQuery{
		config:                    rcq.config,
		ctx:                       rcq.ctx.Clone(),
		order:                     append([]reachablecode.OrderOption{}, rcq.order...),
		inters:                    append([]Interceptor{}, rcq.inters...),
		predicates:                append([]predicate.ReachableCode{}, rcq.predicates...),
		withCertifyVex:            rcq.withCertifyVex.Clone(),
		withReachableCodeArtifact: rcq.withReachableCodeArtifact.Clone(),
		// clone intermediate query.
		sql:  rcq.sql.Clone(),
		path: rcq.path,
	}
}

// WithCertifyVex tells the query-builder to eager-load the nodes that are connected to
// the "certify_vex" edge. The optional arguments are used to configure the query builder of the edge.
func (rcq *ReachableCodeQuery) WithCertifyVex(opts ...func(*CertifyVexQuery)) *ReachableCodeQuery {
	query := (&CertifyVexClient{config: rcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rcq.withCertifyVex = query
	return rcq
}

// WithReachableCodeArtifact tells the query-builder to eager-load the nodes that are connected to
// the "reachable_code_artifact" edge. The optional arguments are used to configure the query builder of the edge.
func (rcq *ReachableCodeQuery) WithReachableCodeArtifact(opts ...func(*ReachableCodeArtifactQuery)) *ReachableCodeQuery {
	query := (&ReachableCodeArtifactClient{config: rcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rcq.withReachableCodeArtifact = query
	return rcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PathToFile string `json:"path_to_file,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReachableCode.Query().
//		GroupBy(reachablecode.FieldPathToFile).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rcq *ReachableCodeQuery) GroupBy(field string, fields ...string) *ReachableCodeGroupBy {
	rcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReachableCodeGroupBy{build: rcq}
	grbuild.flds = &rcq.ctx.Fields
	grbuild.label = reachablecode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PathToFile string `json:"path_to_file,omitempty"`
//	}
//
//	client.ReachableCode.Query().
//		Select(reachablecode.FieldPathToFile).
//		Scan(ctx, &v)
func (rcq *ReachableCodeQuery) Select(fields ...string) *ReachableCodeSelect {
	rcq.ctx.Fields = append(rcq.ctx.Fields, fields...)
	sbuild := &ReachableCodeSelect{ReachableCodeQuery: rcq}
	sbuild.label = reachablecode.Label
	sbuild.flds, sbuild.scan = &rcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReachableCodeSelect configured with the given aggregations.
func (rcq *ReachableCodeQuery) Aggregate(fns ...AggregateFunc) *ReachableCodeSelect {
	return rcq.Select().Aggregate(fns...)
}

func (rcq *ReachableCodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rcq); err != nil {
				return err
			}
		}
	}
	for _, f := range rcq.ctx.Fields {
		if !reachablecode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rcq.path != nil {
		prev, err := rcq.path(ctx)
		if err != nil {
			return err
		}
		rcq.sql = prev
	}
	return nil
}

func (rcq *ReachableCodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReachableCode, error) {
	var (
		nodes       = []*ReachableCode{}
		_spec       = rcq.querySpec()
		loadedTypes = [2]bool{
			rcq.withCertifyVex != nil,
			rcq.withReachableCodeArtifact != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReachableCode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReachableCode{config: rcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(rcq.modifiers) > 0 {
		_spec.Modifiers = rcq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rcq.withCertifyVex; query != nil {
		if err := rcq.loadCertifyVex(ctx, query, nodes,
			func(n *ReachableCode) { n.Edges.CertifyVex = []*CertifyVex{} },
			func(n *ReachableCode, e *CertifyVex) { n.Edges.CertifyVex = append(n.Edges.CertifyVex, e) }); err != nil {
			return nil, err
		}
	}
	if query := rcq.withReachableCodeArtifact; query != nil {
		if err := rcq.loadReachableCodeArtifact(ctx, query, nodes,
			func(n *ReachableCode) { n.Edges.ReachableCodeArtifact = []*ReachableCodeArtifact{} },
			func(n *ReachableCode, e *ReachableCodeArtifact) {
				n.Edges.ReachableCodeArtifact = append(n.Edges.ReachableCodeArtifact, e)
			}); err != nil {
			return nil, err
		}
	}
	for name, query := range rcq.withNamedCertifyVex {
		if err := rcq.loadCertifyVex(ctx, query, nodes,
			func(n *ReachableCode) { n.appendNamedCertifyVex(name) },
			func(n *ReachableCode, e *CertifyVex) { n.appendNamedCertifyVex(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range rcq.withNamedReachableCodeArtifact {
		if err := rcq.loadReachableCodeArtifact(ctx, query, nodes,
			func(n *ReachableCode) { n.appendNamedReachableCodeArtifact(name) },
			func(n *ReachableCode, e *ReachableCodeArtifact) { n.appendNamedReachableCodeArtifact(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range rcq.loadTotal {
		if err := rcq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rcq *ReachableCodeQuery) loadCertifyVex(ctx context.Context, query *CertifyVexQuery, nodes []*ReachableCode, init func(*ReachableCode), assign func(*ReachableCode, *CertifyVex)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*ReachableCode)
	nids := make(map[uuid.UUID]map[*ReachableCode]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(reachablecode.CertifyVexTable)
		s.Join(joinT).On(s.C(certifyvex.FieldID), joinT.C(reachablecode.CertifyVexPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(reachablecode.CertifyVexPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(reachablecode.CertifyVexPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*ReachableCode]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*CertifyVex](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "certify_vex" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (rcq *ReachableCodeQuery) loadReachableCodeArtifact(ctx context.Context, query *ReachableCodeArtifactQuery, nodes []*ReachableCode, init func(*ReachableCode), assign func(*ReachableCode, *ReachableCodeArtifact)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*ReachableCode)
	nids := make(map[uuid.UUID]map[*ReachableCode]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(reachablecode.ReachableCodeArtifactTable)
		s.Join(joinT).On(s.C(reachablecodeartifact.FieldID), joinT.C(reachablecode.ReachableCodeArtifactPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(reachablecode.ReachableCodeArtifactPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(reachablecode.ReachableCodeArtifactPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*ReachableCode]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*ReachableCodeArtifact](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "reachable_code_artifact" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (rcq *ReachableCodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rcq.querySpec()
	if len(rcq.modifiers) > 0 {
		_spec.Modifiers = rcq.modifiers
	}
	_spec.Node.Columns = rcq.ctx.Fields
	if len(rcq.ctx.Fields) > 0 {
		_spec.Unique = rcq.ctx.Unique != nil && *rcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rcq.driver, _spec)
}

func (rcq *ReachableCodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(reachablecode.Table, reachablecode.Columns, sqlgraph.NewFieldSpec(reachablecode.FieldID, field.TypeUUID))
	_spec.From = rcq.sql
	if unique := rcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rcq.path != nil {
		_spec.Unique = true
	}
	if fields := rcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reachablecode.FieldID)
		for i := range fields {
			if fields[i] != reachablecode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rcq *ReachableCodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rcq.driver.Dialect())
	t1 := builder.Table(reachablecode.Table)
	columns := rcq.ctx.Fields
	if len(columns) == 0 {
		columns = reachablecode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rcq.sql != nil {
		selector = rcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rcq.ctx.Unique != nil && *rcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rcq.predicates {
		p(selector)
	}
	for _, p := range rcq.order {
		p(selector)
	}
	if offset := rcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedCertifyVex tells the query-builder to eager-load the nodes that are connected to the "certify_vex"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (rcq *ReachableCodeQuery) WithNamedCertifyVex(name string, opts ...func(*CertifyVexQuery)) *ReachableCodeQuery {
	query := (&CertifyVexClient{config: rcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if rcq.withNamedCertifyVex == nil {
		rcq.withNamedCertifyVex = make(map[string]*CertifyVexQuery)
	}
	rcq.withNamedCertifyVex[name] = query
	return rcq
}

// WithNamedReachableCodeArtifact tells the query-builder to eager-load the nodes that are connected to the "reachable_code_artifact"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (rcq *ReachableCodeQuery) WithNamedReachableCodeArtifact(name string, opts ...func(*ReachableCodeArtifactQuery)) *ReachableCodeQuery {
	query := (&ReachableCodeArtifactClient{config: rcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if rcq.withNamedReachableCodeArtifact == nil {
		rcq.withNamedReachableCodeArtifact = make(map[string]*ReachableCodeArtifactQuery)
	}
	rcq.withNamedReachableCodeArtifact[name] = query
	return rcq
}

// ReachableCodeGroupBy is the group-by builder for ReachableCode entities.
type ReachableCodeGroupBy struct {
	selector
	build *ReachableCodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rcgb *ReachableCodeGroupBy) Aggregate(fns ...AggregateFunc) *ReachableCodeGroupBy {
	rcgb.fns = append(rcgb.fns, fns...)
	return rcgb
}

// Scan applies the selector query and scans the result into the given value.
func (rcgb *ReachableCodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rcgb.build.ctx, ent.OpQueryGroupBy)
	if err := rcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReachableCodeQuery, *ReachableCodeGroupBy](ctx, rcgb.build, rcgb, rcgb.build.inters, v)
}

func (rcgb *ReachableCodeGroupBy) sqlScan(ctx context.Context, root *ReachableCodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rcgb.fns))
	for _, fn := range rcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rcgb.flds)+len(rcgb.fns))
		for _, f := range *rcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReachableCodeSelect is the builder for selecting fields of ReachableCode entities.
type ReachableCodeSelect struct {
	*ReachableCodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rcs *ReachableCodeSelect) Aggregate(fns ...AggregateFunc) *ReachableCodeSelect {
	rcs.fns = append(rcs.fns, fns...)
	return rcs
}

// Scan applies the selector query and scans the result into the given value.
func (rcs *ReachableCodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rcs.ctx, ent.OpQuerySelect)
	if err := rcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReachableCodeQuery, *ReachableCodeSelect](ctx, rcs.ReachableCodeQuery, rcs, rcs.inters, v)
}

func (rcs *ReachableCodeSelect) sqlScan(ctx context.Context, root *ReachableCodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rcs.fns))
	for _, fn := range rcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
