// Code generated by ent, DO NOT EDIT.

package potentialmitigation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the potentialmitigation type in the database.
	Label = "potential_mitigation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPhase holds the string denoting the phase field in the database.
	FieldPhase = "phase"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldEffectiveness holds the string denoting the effectiveness field in the database.
	FieldEffectiveness = "effectiveness"
	// FieldEffectivenessNotes holds the string denoting the effectiveness_notes field in the database.
	FieldEffectivenessNotes = "effectiveness_notes"
	// EdgeCwe holds the string denoting the cwe edge name in mutations.
	EdgeCwe = "cwe"
	// Table holds the table name of the potentialmitigation in the database.
	Table = "potential_mitigations"
	// CweTable is the table that holds the cwe relation/edge. The primary key declared below.
	CweTable = "cwe_potential_mitigation"
	// CweInverseTable is the table name for the CWE entity.
	// It exists in this package in order to avoid circular dependency with the "cwe" package.
	CweInverseTable = "cw_es"
)

// Columns holds all SQL columns for potentialmitigation fields.
var Columns = []string{
	FieldID,
	FieldPhase,
	FieldDescription,
	FieldEffectiveness,
	FieldEffectivenessNotes,
}

var (
	// CwePrimaryKey and CweColumn2 are the table columns denoting the
	// primary key for the cwe relation (M2M).
	CwePrimaryKey = []string{"cwe_id", "potential_mitigation_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PotentialMitigation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPhase orders the results by the phase field.
func ByPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhase, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByEffectiveness orders the results by the effectiveness field.
func ByEffectiveness(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveness, opts...).ToFunc()
}

// ByEffectivenessNotes orders the results by the effectiveness_notes field.
func ByEffectivenessNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectivenessNotes, opts...).ToFunc()
}

// ByCweCount orders the results by cwe count.
func ByCweCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCweStep(), opts...)
	}
}

// ByCwe orders the results by cwe terms.
func ByCwe(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCweStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCweStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CweInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, CweTable, CwePrimaryKey...),
	)
}
