// Code generated by ent, DO NOT EDIT.

package demonstrativeexample

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldLTE(FieldID, id))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldEQ(FieldDescription, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.FieldContainsFold(FieldDescription, v))
}

// HasCwe applies the HasEdge predicate on the "cwe" edge.
func HasCwe() predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, CweTable, CwePrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCweWith applies the HasEdge predicate on the "cwe" edge with a given conditions (other predicates).
func HasCweWith(preds ...predicate.CWE) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(func(s *sql.Selector) {
		step := newCweStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DemonstrativeExample) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DemonstrativeExample) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DemonstrativeExample) predicate.DemonstrativeExample {
	return predicate.DemonstrativeExample(sql.NotPredicates(p))
}
